services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=dbKeenayEducation
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5434:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks:
      - app-network

  minio:
    image: cleanstart/minio:latest
    container_name: minio
    user: "0:0"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1234567890
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  tarantool:
    build:
      context: .
      dockerfile: Dockerfile.tarantool
    container_name: my-tarantool
    working_dir: /opt/tarantool
    ports:
      - "3301:3301"
    volumes:
      - tarantool_data:/var/lib/tarantool
    command: tarantool --name instance-001 --config /opt/tarantool/config.yaml

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  minio_data:
  tarantool_data: