spring:
  data:
    tarantool:
      host: localhost
      port: 3302
      username: app
      password: admin
  servlet:
    multipart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5434/dbKeenayEducation
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: demo
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  security:
    key: 8074658237c236e39e96e909ac1abb25a3e1773b100096ad6877c439cd452c17
    days: 7
  rabbitmq:
    username: admin
    password: admin
    host: localhost
    port: 5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: seaoffriendsforyou@gmail.com
    password: nzzaltcjgbzgfwyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    default-encoding: UTF-8

server:
  port: 8080

rabbitmq:
  queue:
    name: email-send
    name-retry: email-retry
    name-exception: email-exception
    retry-attempt: 5
    time-retry: 30000
  stomp:
    host: localhost
    port: 61613
    login: admin
    passcode: admin

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: 1234567890
  bucket-name: bucket
  day-life: 7

logging:
  level:
    keenay.education: INFO
    io.tarantool: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%mdc] %msg%n"