credentials:
  users:
    app:
      password: 'admin'
      roles: [super, sharding]

iproto:
  advertise:
    peer:
      login: app
    sharding:
      login: app

sharding:
  bucket_count: 3000

replication:
  failover: manual

groups:
  storages:
    sharding:
      roles: [storage]
    roles: [roles.crud-storage]
    app:
      file: /opt/tarantool/init.lua
    replicasets:
      storage-rs-001:
        leader: instance-001
        instances:
          instance-001:
            iproto:
              listen:
                - uri: '0.0.0.0:3301'
              advertise:
                sharding:
                  uri: 'my-tarantool-storage:3301'

  routers:
    sharding:
      roles: [router]
    roles: [roles.crud-router]
    replicasets:
      router-rs-001:
        leader: router-001
        instances:
          router-001:
            iproto:
              listen:
                - uri: '0.0.0.0:3302'
              advertise:
                sharding:
                  uri: 'my-tarantool-router:3302'